// Generated by CoffeeScript 1.6.3
var memoryCache;

memoryCache = require('memory-cache');

exports.fetch = function(key, fn, params, cacheCallback) {
  var cb;
  if (memoryCache.get(key)) {
    return cacheCallback(memoryCache.get(key));
  }
  cb = function(returned_val) {
    memoryCache.put(key, returned_val);
    return cacheCallback(returned_val);
  };
  params.push(cb);
  return fn.apply(null, params);
};

exports.clear = function() {
  return memoryCache.clear();
};

exports.remove = function(key) {
  return memoryCache.del(key);
};

exports.size = function() {
  return memoryCache.size();
};
