// Generated by CoffeeScript 1.6.3
var clear, fetch, memoryCache, remove, size;

memoryCache = require('memory-cache');

fetch = function(key, fn, params, cacheCallback) {
  var cb;
  if (memoryCache.get(key)) {
    return cacheCallback(memoryCache.get(key));
  }
  cb = function(returned_val) {
    console.log('in cb', returned_val);
    memoryCache.put(key, returned_val);
    return cacheCallback(returned_val);
  };
  params.push(cb);
  return fn.apply(null, params);
};

clear = function() {
  return memoryCache.clear();
};

remove = function(key) {
  return memoryCache.del(key);
};

size = function() {
  return memoryCache.size();
};

exports.fetch = fetch;

exports.clear = clear;

exports.remove = remove;

exports.size = size;
